### ISSUE TITLE
More details about the data and how to use them

### ISSUE THREAD

**Issue by haozheji** [JasonForJoy/FIRE#1]
Hi, I downloaded the data and for each split it has 7 versions. `both`, `other`, `self` with original and revised version and `none` with only original version. I saw the code of training and testing only uses the ones with `self` tag. So what are the differences between these four types? Is it I only need to use the `self` ones in order to compare with the results in the paper?

**Comment by JasonForJoy** [comment]
@cdjhz 
Hi! Thanks for your interest in our work.
```self``` and ```other``` denote the persona role. ```original``` and ```revised``` denote the degree of difficulty to understand the persona decsriptions (```revised``` is a more challenging setting). 
You can use different combinations as you want. 
In our experiments, we followed previous studies by training and testing with the same ```self``` + ```original``` (or ```self``` + ```revised```) to keep training and tesing consistent. 
You can aslo perform the transfer experiments by training with ```self``` + ```original``` and testing with ```self``` + ```revised```.

**Comment by haozheji** [comment]
Thank you very much!
